// DO NOT EDIT THIS FILE

const fs = require("fs");
const postcss = require("postcss");

const css = fs.readFileSync("./index.css", "utf-8");

describe("quiz 02 - CSS", () => {
  let root;

  beforeAll(() => {
    root = postcss.parse(css);
  });

  test("The '.menu' should have the required styles", () => {
    const menu = root.nodes.find(node => node.selector === ".menu");
    expect(menu).not.toBeUndefined();

    const hasPosition = menu.nodes.some(node => node.prop === "position" && node.value === "sticky");
    const hasTop = menu.nodes.some(node => node.prop === "top" && node.value === "0");

    expect(hasPosition).toBe(true);
    expect(hasTop).toBe(true);
  });
});
